-- ════════════════════════════════════════════════════════════
-- REMOTECARE · Database Seed
-- NO FAKE DATA - Production ready
-- ════════════════════════════════════════════════════════════

-- ⚠️  IMPORTANT: This file contains NO default data
-- 
-- Superadmin must be created via ONE of these methods:
-- 
-- METHOD 1: SQL Insert (run in Supabase Dashboard → SQL Editor)
--    Generate hash: console.log(await hashPassword('your-password')) in browser
--    Then insert:
--
--    INSERT INTO users (username, password, role, display_name, is_super_admin)
--    VALUES ('superadmin', '$2a$10$...HASH...', 'admin', 'Super Admin', TRUE);
--
-- METHOD 2: First-time registration (app auto-detects empty database)
--    The app will show "First Setup" wizard if no users exist
--
-- METHOD 3: Environment variable (Vercel)
--    Set VITE_SUPERADMIN_PASSWORD in Vercel dashboard
--    App hashes and stores on first boot

-- No default hospitals - create via Admin → Directory → Hospitals
-- No default patients - all real enrollment data only
